# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotty" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "965981b7e879ebe2592e1cd8d153a687525f7c14f930e4eaa2e59da005156b0d"
      url "https://github.com/bitwise-media-group/dotty/releases/download/v#{version}/dotty_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0bccc688575024e5ce6786942f80f0d9f2ca6ee491faf71a2e6c6144156c7204"
      url "https://github.com/bitwise-media-group/dotty/releases/download/v#{version}/dotty_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5c1510b6b5f9ec6be2df6d251e4811aa2a2915f70437dfc094ef1430025f178d"
      url "https://github.com/bitwise-media-group/dotty/releases/download/v#{version}/dotty_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "158329a77971747056b9ecf76eef802997dffa5cf18d68a205619236f2df4f96"
      url "https://github.com/bitwise-media-group/dotty/releases/download/v#{version}/dotty_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dotty"
  desc "Terminal-driven dotfiles workflow — portable profiles, reproducible Brewfiles, and YubiKey-backed SSH signing keys"
  homepage "https://github.com/bitwise-media-group/dotty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dotty"
  manpage "docs/man/dotty-brewfile-add.1"
  manpage "docs/man/dotty-brewfile-dump.1"
  manpage "docs/man/dotty-brewfile-edit.1"
  manpage "docs/man/dotty-brewfile-sync.1"
  manpage "docs/man/dotty-brewfile-upgrade.1"
  manpage "docs/man/dotty-brewfile.1"
  manpage "docs/man/dotty-completion-bash.1"
  manpage "docs/man/dotty-completion-fish.1"
  manpage "docs/man/dotty-completion-powershell.1"
  manpage "docs/man/dotty-completion-zsh.1"
  manpage "docs/man/dotty-completion.1"
  manpage "docs/man/dotty-dotfiles-link.1"
  manpage "docs/man/dotty-dotfiles-restore.1"
  manpage "docs/man/dotty-dotfiles-status.1"
  manpage "docs/man/dotty-dotfiles.1"
  manpage "docs/man/dotty-env-add.1"
  manpage "docs/man/dotty-env-get.1"
  manpage "docs/man/dotty-env-list.1"
  manpage "docs/man/dotty-env-remove.1"
  manpage "docs/man/dotty-env-run.1"
  manpage "docs/man/dotty-env-use.1"
  manpage "docs/man/dotty-env.1"
  manpage "docs/man/dotty-git-append.1"
  manpage "docs/man/dotty-git-browse.1"
  manpage "docs/man/dotty-git-done.1"
  manpage "docs/man/dotty-git-down.1"
  manpage "docs/man/dotty-git-expand.1"
  manpage "docs/man/dotty-git-merge.1"
  manpage "docs/man/dotty-git-propose.1"
  manpage "docs/man/dotty-git-resign.1"
  manpage "docs/man/dotty-git-start.1"
  manpage "docs/man/dotty-git-status.1"
  manpage "docs/man/dotty-git-switch.1"
  manpage "docs/man/dotty-git-sync.1"
  manpage "docs/man/dotty-git-up.1"
  manpage "docs/man/dotty-git.1"
  manpage "docs/man/dotty-init.1"
  manpage "docs/man/dotty-profile-activate.1"
  manpage "docs/man/dotty-profile-delete.1"
  manpage "docs/man/dotty-profile-get.1"
  manpage "docs/man/dotty-profile-list.1"
  manpage "docs/man/dotty-profile-new.1"
  manpage "docs/man/dotty-profile.1"
  manpage "docs/man/dotty-security-key-add.1"
  manpage "docs/man/dotty-security-key-allow.1"
  manpage "docs/man/dotty-security-key-disallow.1"
  manpage "docs/man/dotty-security-key-remove.1"
  manpage "docs/man/dotty-security-key.1"
  manpage "docs/man/dotty-signing-key-authorize.1"
  manpage "docs/man/dotty-signing-key-get.1"
  manpage "docs/man/dotty-signing-key-import.1"
  manpage "docs/man/dotty-signing-key-link.1"
  manpage "docs/man/dotty-signing-key-list.1"
  manpage "docs/man/dotty-signing-key-new.1"
  manpage "docs/man/dotty-signing-key-sign.1"
  manpage "docs/man/dotty-signing-key-trust.1"
  manpage "docs/man/dotty-signing-key.1"
  manpage "docs/man/dotty-tmux-new.1"
  manpage "docs/man/dotty-tmux.1"
  manpage "docs/man/dotty-worktree-end.1"
  manpage "docs/man/dotty-worktree-start.1"
  manpage "docs/man/dotty-worktree.1"
  manpage "docs/man/dotty.1"
  bash_completion "completions/dotty.bash"
  fish_completion "completions/dotty.fish"
  zsh_completion "completions/dotty.zsh"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dotty"]
    end
  end

  # No zap stanza required

end
