# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotty" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "8337ff3e2a6e5324609f2971d62f85c75a5e25db8f57628f50b2526d48208750"
      url "https://github.com/bitwise-media-group/dotty/releases/download/v#{version}/dotty_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ecd79841564908727bfa3cdcba7acbdf408f365cfd767b2d7f288119d552f631"
      url "https://github.com/bitwise-media-group/dotty/releases/download/v#{version}/dotty_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f30707436b80ae4eaa1a7b17d89ada6d30c25aad8d93e8cd667511b9d816cc3f"
      url "https://github.com/bitwise-media-group/dotty/releases/download/v#{version}/dotty_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "67ea3d3a89fd9f2e7c3b0eb36d16491e6fb5e9e5960346567c7bda66eb394565"
      url "https://github.com/bitwise-media-group/dotty/releases/download/v#{version}/dotty_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dotty"
  desc "Terminal-driven dotfiles workflow — portable profiles, reproducible Brewfiles, and YubiKey-backed SSH signing keys"
  homepage "https://github.com/bitwise-media-group/dotty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dotty"
  manpage "docs/man/dotty-brewfile-add.1"
  manpage "docs/man/dotty-brewfile-dump.1"
  manpage "docs/man/dotty-brewfile-edit.1"
  manpage "docs/man/dotty-brewfile-sync.1"
  manpage "docs/man/dotty-brewfile-upgrade.1"
  manpage "docs/man/dotty-brewfile.1"
  manpage "docs/man/dotty-completion-bash.1"
  manpage "docs/man/dotty-completion-fish.1"
  manpage "docs/man/dotty-completion-powershell.1"
  manpage "docs/man/dotty-completion-zsh.1"
  manpage "docs/man/dotty-completion.1"
  manpage "docs/man/dotty-dotfiles-link.1"
  manpage "docs/man/dotty-dotfiles-restore.1"
  manpage "docs/man/dotty-dotfiles-status.1"
  manpage "docs/man/dotty-dotfiles.1"
  manpage "docs/man/dotty-env-add.1"
  manpage "docs/man/dotty-env-get.1"
  manpage "docs/man/dotty-env-list.1"
  manpage "docs/man/dotty-env-remove.1"
  manpage "docs/man/dotty-env-run.1"
  manpage "docs/man/dotty-env-use.1"
  manpage "docs/man/dotty-env.1"
  manpage "docs/man/dotty-git-append.1"
  manpage "docs/man/dotty-git-browse.1"
  manpage "docs/man/dotty-git-done.1"
  manpage "docs/man/dotty-git-down.1"
  manpage "docs/man/dotty-git-expand.1"
  manpage "docs/man/dotty-git-merge.1"
  manpage "docs/man/dotty-git-propose.1"
  manpage "docs/man/dotty-git-resign.1"
  manpage "docs/man/dotty-git-start.1"
  manpage "docs/man/dotty-git-status.1"
  manpage "docs/man/dotty-git-switch.1"
  manpage "docs/man/dotty-git-sync.1"
  manpage "docs/man/dotty-git-up.1"
  manpage "docs/man/dotty-git.1"
  manpage "docs/man/dotty-init.1"
  manpage "docs/man/dotty-profile-activate.1"
  manpage "docs/man/dotty-profile-new.1"
  manpage "docs/man/dotty-profile.1"
  manpage "docs/man/dotty-security-key-add.1"
  manpage "docs/man/dotty-security-key-allow.1"
  manpage "docs/man/dotty-security-key-disallow.1"
  manpage "docs/man/dotty-security-key-remove.1"
  manpage "docs/man/dotty-security-key.1"
  manpage "docs/man/dotty-signing-key-authorize.1"
  manpage "docs/man/dotty-signing-key-get.1"
  manpage "docs/man/dotty-signing-key-import.1"
  manpage "docs/man/dotty-signing-key-link.1"
  manpage "docs/man/dotty-signing-key-list.1"
  manpage "docs/man/dotty-signing-key-new.1"
  manpage "docs/man/dotty-signing-key-sign.1"
  manpage "docs/man/dotty-signing-key-trust.1"
  manpage "docs/man/dotty-signing-key.1"
  manpage "docs/man/dotty-tmux-new.1"
  manpage "docs/man/dotty-tmux.1"
  manpage "docs/man/dotty-worktree-end.1"
  manpage "docs/man/dotty-worktree-start.1"
  manpage "docs/man/dotty-worktree.1"
  manpage "docs/man/dotty.1"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dotty"]
    end
  end

  generate_completions_from_executable "dotty",
    shell_parameter_format: :cobra

  # No zap stanza required

end
