# This file was generated by GoReleaser. DO NOT EDIT.
cask "evolve" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "28cc7b6678f1ef816601a334acf20b9ce892af005c3d609a82de4f0ada4d6673"
      url "https://github.com/bitwise-media-group/evolve/releases/download/v#{version}/evolve_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d8ff511609b474a2de9272523b6031b1b197863c334c272388e2a3389b4c97f6"
      url "https://github.com/bitwise-media-group/evolve/releases/download/v#{version}/evolve_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8b6bfeead260164b08cb4c1ffc765a61dd70675b12a914c3cb7c162f171180b7"
      url "https://github.com/bitwise-media-group/evolve/releases/download/v#{version}/evolve_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "03d08a84728d2eff07ca236267426c7bcec0442c789e05d47486f262e322b397"
      url "https://github.com/bitwise-media-group/evolve/releases/download/v#{version}/evolve_#{version}_linux_arm64.tar.gz"
    end
  end

  name "evolve"
  desc "Evaluate coding-agent plugins — static checks, trigger-accuracy evals, behavioral cases, and reports"
  homepage "https://github.com/bitwise-media-group/evolve"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "evolve"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/evolve"]
    end
  end

  generate_completions_from_executable "evolve",
    shell_parameter_format: :cobra

  # No zap stanza required

end
