# This file was generated by GoReleaser. DO NOT EDIT.
cask "evolve" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "5c1db5275af1d0707e87084901b12d06e7342b892a66660fe1d447f49036a865"
      url "https://github.com/bitwise-media-group/evolve/releases/download/v#{version}/evolve_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7d7910bb036657ed9a4c981a7593b44d092e8be52294bbd998d753958c85c612"
      url "https://github.com/bitwise-media-group/evolve/releases/download/v#{version}/evolve_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "00b5daaac648bc3643c88f7f54115fe18e4f81ef9cef9c795b52874034af812b"
      url "https://github.com/bitwise-media-group/evolve/releases/download/v#{version}/evolve_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b18dd89c196e21ae8cdc5f3a5e3028935239e6d14e417dfc76ddbe4de138fa85"
      url "https://github.com/bitwise-media-group/evolve/releases/download/v#{version}/evolve_#{version}_linux_arm64.tar.gz"
    end
  end

  name "evolve"
  desc "Evaluate coding-agent plugins — static checks, trigger-accuracy evals, behavioral cases, and reports"
  homepage "https://github.com/bitwise-media-group/evolve"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "evolve"
  manpage "docs/man/evolve-completion-bash.1"
  manpage "docs/man/evolve-completion-fish.1"
  manpage "docs/man/evolve-completion-powershell.1"
  manpage "docs/man/evolve-completion-zsh.1"
  manpage "docs/man/evolve-completion.1"
  manpage "docs/man/evolve-doctor.1"
  manpage "docs/man/evolve-models-discover.1"
  manpage "docs/man/evolve-models.1"
  manpage "docs/man/evolve-report.1"
  manpage "docs/man/evolve-run-all.1"
  manpage "docs/man/evolve-run-check.1"
  manpage "docs/man/evolve-run-checks.1"
  manpage "docs/man/evolve-run-evals.1"
  manpage "docs/man/evolve-run-triggers.1"
  manpage "docs/man/evolve-run.1"
  manpage "docs/man/evolve-version.1"
  manpage "docs/man/evolve-view.1"
  manpage "docs/man/evolve.1"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/evolve"]
    end
  end

  generate_completions_from_executable "evolve",
    shell_parameter_format: :cobra

  # No zap stanza required

end
