# This file was generated by GoReleaser. DO NOT EDIT.
cask "evolve" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "9467934e6ab84a697affb5844ba8a1084d0d1905d1ea5efb9b2fa5fc1662e08f"
      url "https://github.com/bitwise-media-group/evolve/releases/download/v#{version}/evolve_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d60ebda89c4316806a29133aee7206ddc417ab581e89dcb9e56845f32504661"
      url "https://github.com/bitwise-media-group/evolve/releases/download/v#{version}/evolve_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "99ed0487026909ed5baac8226127d4249ac567c8d17c6f820f879f868bb77f3d"
      url "https://github.com/bitwise-media-group/evolve/releases/download/v#{version}/evolve_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "327b5f87154316040467b720f22b9533a69594c747280eb4158ef8b49477139f"
      url "https://github.com/bitwise-media-group/evolve/releases/download/v#{version}/evolve_#{version}_linux_arm64.tar.gz"
    end
  end

  name "evolve"
  desc "Evaluate coding-agent plugins — static checks, trigger-accuracy evals, behavioral cases, and reports"
  homepage "https://github.com/bitwise-media-group/evolve"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "evolve"
  manpage "docs/man/evolve-completion-bash.1"
  manpage "docs/man/evolve-completion-fish.1"
  manpage "docs/man/evolve-completion-powershell.1"
  manpage "docs/man/evolve-completion-zsh.1"
  manpage "docs/man/evolve-completion.1"
  manpage "docs/man/evolve-doctor.1"
  manpage "docs/man/evolve-models.1"
  manpage "docs/man/evolve-report.1"
  manpage "docs/man/evolve-run-all.1"
  manpage "docs/man/evolve-run-check.1"
  manpage "docs/man/evolve-run-checks.1"
  manpage "docs/man/evolve-run-evals.1"
  manpage "docs/man/evolve-run-triggers.1"
  manpage "docs/man/evolve-run.1"
  manpage "docs/man/evolve-version.1"
  manpage "docs/man/evolve-view.1"
  manpage "docs/man/evolve.1"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/evolve"]
    end
  end

  generate_completions_from_executable "evolve",
    shell_parameter_format: :cobra

  # No zap stanza required

end
