# This file was generated by GoReleaser. DO NOT EDIT.
cask "patchy" do
  version "0.8.2"

  on_macos do
    on_intel do
      sha256 "8f739ce789e5d736ef6cd158ad5f6e286374ee50b8f260621670584056fe392c"
      url "https://github.com/bitwise-media-group/patchy/releases/download/v#{version}/patchy-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c6e0d4828ae71ea40568cfa2f98688faa0988106dd42cdd19c6d518e79cff608"
      url "https://github.com/bitwise-media-group/patchy/releases/download/v#{version}/patchy-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "807b16eeccba2c9d0f1835354e2f0be32a578a169dee83ad797c984e54842fd4"
      url "https://github.com/bitwise-media-group/patchy/releases/download/v#{version}/patchy-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a85245f60b2f6a09ec77042f1416ff2b4895146b3dc64d534285cea8b3f4ce17"
      url "https://github.com/bitwise-media-group/patchy/releases/download/v#{version}/patchy-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "patchy"
  desc "Triage and remediate security findings from the terminal, over your own kubeconfig"
  homepage "https://github.com/bitwise-media-group/patchy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "patchy"
  binary "kubectl-patchy"
  binary "completions/kubectl_complete-patchy"
  bash_completion "completions/patchy.bash"
  fish_completion "completions/patchy.fish"
  zsh_completion "completions/patchy.zsh"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/patchy", "#{staged_path}/kubectl-patchy", "#{staged_path}/completions/kubectl_complete-patchy"]
    end
  end

  # No zap stanza required

end
