# This file was generated by GoReleaser. DO NOT EDIT.
cask "patchy" do
  version "0.10.1"

  on_macos do
    on_intel do
      sha256 "b668a6242d09f1cc1369f49c19c522e2284713d1587c6f4f7efea68973e6b6d3"
      url "https://github.com/bitwise-media-group/patchy/releases/download/v#{version}/patchy-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "66664006769f94535ef1dd91bb0df99aa81c5887b615fbddfdb7239d69822744"
      url "https://github.com/bitwise-media-group/patchy/releases/download/v#{version}/patchy-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f0e9ecf690137642aaf78f2d9b5ab82db26f6181882392617bf46b32be2bf79e"
      url "https://github.com/bitwise-media-group/patchy/releases/download/v#{version}/patchy-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9fe77b8745a940d55acd7b1761dc522f69424eec79ca6d42761c5771852bb0db"
      url "https://github.com/bitwise-media-group/patchy/releases/download/v#{version}/patchy-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "patchy"
  desc "Triage and remediate security findings from the terminal, over your own kubeconfig"
  homepage "https://github.com/bitwise-media-group/patchy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "patchy"
  binary "kubectl-patchy"
  binary "completions/kubectl_complete-patchy"
  bash_completion "completions/patchy.bash"
  fish_completion "completions/patchy.fish"
  zsh_completion "completions/patchy.zsh"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/patchy", "#{staged_path}/kubectl-patchy", "#{staged_path}/completions/kubectl_complete-patchy"]
    end
  end

  # No zap stanza required

end
