# This file was generated by GoReleaser. DO NOT EDIT.
cask "patchy" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "b8f67c7ed4a9eb949ffa1f70ae35ce0c7954ff0443fe1986d9b7552d46e01c8c"
      url "https://github.com/bitwise-media-group/patchy/releases/download/v#{version}/patchy-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab76a925aa6c02b38b28158f5d24fe5c80d04ea35740c621f1d96b29206c7493"
      url "https://github.com/bitwise-media-group/patchy/releases/download/v#{version}/patchy-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ba0820fe1f9d6097a4e21bf2aadb14ca561d7c8734f7c631ea5f5bb10f77b62e"
      url "https://github.com/bitwise-media-group/patchy/releases/download/v#{version}/patchy-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c28e6ab55523940b8f2b5f2acb54283f36035ed1d75121568f50407221d88325"
      url "https://github.com/bitwise-media-group/patchy/releases/download/v#{version}/patchy-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "patchy"
  desc "Triage and remediate security findings from the terminal, over your own kubeconfig"
  homepage "https://github.com/bitwise-media-group/patchy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "patchy"
  binary "kubectl-patchy"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/patchy", "#{staged_path}/kubectl-patchy"]
    end
  end

  # No zap stanza required

end
